# LOAD PACKAGES -----
library(shiny)
library(shinydashboard)
library(tidyverse)
#library(leaflet)
library(shinycssloaders)
library(raster)
library(sp)
library(tmap)
library(sf)
library(stars)
library(gstat)
library(rgdal)

# READ IN DATA ----
kelp_df <- readRDS(here::here("demo_rasters", "kelp_df.rds"))
kelp_raster <- raster(here::here("demo_rasters", "kelp_raster.tiff"))
depth_raster <- raster(here::here("demo_rasters", "depth_raster.tiff"))
sst_raster <- raster(here::here("demo_rasters", "sst_raster.tiff"))
NO3_raster <- raster(here::here("demo_rasters", "NO3_raster.tiff"))
NO2_raster <- raster(here::here("demo_rasters", "NO2_raster.tiff"))
NH4_raster <- raster(here::here("demo_rasters", "NH4_raster.tiff"))
channel_islands <- st_read(here::here("CI_data", "channel_islands.shp"))
area_sf <- readRDS(here::here("demo_rasters", "area_sf.rds"))
data("World")
resto_model_raster <- raster(here::here("demo_rasters", "resto_model_raster.tiff"))
harvest_model_raster <- raster(here::here("demo_rasters", "harvest_model_raster.tiff"))